### ISSUE TITLE
Improvements in github actions

### ISSUE THREAD

**Issue by ayusharma** [trivago/melody#119]
#### Explain the problem
- [ ] When there is merge in master, actions runs twice. Ref: https://github.com/actions/bin/issues/36
- [ ] when pull request is opened from fork, then PR branch is not checked out.  More info https://github.com/gr2m/git-checkout-pull-request-action
- [ ] On pull request, Action status is not visible, but they run in background  https://github.com/trivago/melody/pull/122 😮 

#### Todo

- [ ] Also in release action, move up `filter commit message` level 1 
- [ ] Filter PR on node6,10,11 action
- [ ] Add https://github.com/actions/bin/tree/master/filter#merged filter
- [ ] Adds coveralls (coverage) for github actions

#### Expected Behaviour
Not required

#### Actual Behaviour
Not required

#### Steps to reproduce
Not required

#### Provide a repository that reproduces issue if possible
Not required

#### Provide your Environment details
Not required
